### ISSUE TITLE
LI-USB30-IMX390 support?

### ISSUE THREAD

**Issue by linknum23** [LI01/linux_camera_tool#14]
I followed your readme and built leopard_cam using cmake on Ubuntu 18.04 , however I have not been able to see anything in the image viewer, which tends to disappear over half the time this is launched or show a completely black image (even with autoexposure checked, trying all Sensor Datatype/Raw Camera Pixel Format combinations). I have attempted launching leopard_cam with and without superuser permissions.

Here is a typical output of a command:

   
    sudo -H ./leopard_cam -d 2
    ********************Udev Device Start************************
    Device Node Path: /dev/video0
    Device Node Path: /dev/video1
    Device Node Path: /dev/video2
    Find leopard USB3 camera at /dev/video2
      VID/PID: 2a0b 00c7
      Leopard Imaging
      LI-IMX390
    ********************Camera Tool Usages***********************
    Usage: ./leopard_cam [options]
    Supported options:
    -n, --nbufs n		Set the number of video buffers
    -s, --size WxH		Set the frame size
    -t, --time-per-frame	Set the time per frame (eg. 25 = 25 fps)
    -d, --device n          Set device number to /dev/videon
    -h, --help			    Show this help screen
    ********************List Available Resolutions***************
    Resolution:1936x1100
    hardware rev=102
    firmware rev=0
    uuid=e181119b-f485-4571-83a5-eba82b028193-20200302����@��
    ********************Device Infomation************************
    Does not support read, try with mmap
    
    Get Current Video Format:YUYV (56595559)1936x1100
    byte per line:3872
    size image:4259200
    ********************Allocate Buffer for Capturing************
    2 buffers requested.
    length: 4259200 offset: 0
    Buffer mapped at address 0x7f5b78065000.
    length: 4259200 offset: 4259840
    Buffer mapped at address 0x7f5b6b05f000.
    ********************Control Logs*****************************
    
    (Camera View:21210): GLib-GObject-CRITICAL **: 15:55:59.092: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
    Get Current Frame Rate = 30
    resize window enable
    Stream info display enable enable

Are there any tips that you suggest to make this work?

For reference I am using the latest commit to master: hash=abe41ac1fe2ac98147d6af1d282714455975ac86

Simplified output of uname -a on my machine: Linux 5.3.0-40-generic #32~18.04.1-Ubuntu SMP  x86_64 GNU/Linux

**Comment by mhungerford-cpi** [comment]
Same issue here, except the camera preview window crashes within a second of the UI being launched, and can't be relaunched.

I get this error (same as above):
(Camera View:12943): GLib-GObject-CRITICAL **: 18:09:37.751: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

Build from master on Ubuntu 18.04.  Using IMX-327 with USB bridge.

Camera almost works with qv4l2, except everything is green due to wrong video mode or bayer filter being necessary.

**Comment by linknum23** [comment]
@mhungerford-cpi I have also had the same issue there the preview window crashes. I don't know what makes the window crash sometimes, but other times just show nothing.

**Comment by danyu9394** [comment]
Hi, 
I had this issue as well with some newer version of OpenCV. Three possible solutions:
1. sometimes `make` works when `cmake` produce this problem, but it is quite unlikely it will work
2. Use an old OpenCV build like `3.4.2`
3. Run it on docker using the old image `sudo docker pull danyu9394/linux_camera_tool:latest` then git pull to get the latest version

**Comment by linknum23** [comment]
I am actually using an older version of opencv, 3.2.0, looking through the README this does not appear to be supported. I will confirm whether or not this works in docker and update this issue.

**Comment by mhungerford-cpi** [comment]
opencv-3.2.0 is the current version shipped by the Ubuntu LTS (18.04).  Most enterprise Linux user run the LTS (Long-Term-Supported) version of Ubuntu.  We use it on our development systems and build servers.

**Comment by mhungerford-cpi** [comment]
I now have the application working on Ubuntu 18.04.  
I'm not sure what fixed it, I tried the camera while in Windows (dual-boot), I unplugged the camera, and I now force the camera to the lowest resolution (1948x1108).
Any higher size and the window still crashes.  I don't know what was causing the gobject error, but it was on every launch yesterday (tried at least a dozen times).

**Comment by mhungerford-cpi** [comment]
I figured it out, there is a binary checked-in (leopard_cam).  That one works and the window doesn't crash.  The one I built myself crashes.  Both link to the same versions of libraries.

**Comment by danyu9394** [comment]
On my setup, OpenCV 3.4.2 runs fine with high resolution(4k). And many of my coworkers' ubuntu machine. But there was a time it didn't work, my coworker ended up reinstalling the ubuntu to fix it, was using 18.04 and 3.4.2. 
I haven't really be able to solve this environment issue. That's why I would recommend using docker if you don't want to switch your OpenCV version.
Also using the check-in binary is a quick way to fix the problem!

**Comment by linknum23** [comment]
Hmm I am still having issues seeing anything at all even in docker, I will try this on another computer. Thanks for the support.

**Comment by linknum23** [comment]
I had all of the same problems on another co-workers computer. Could either of your verify that they are using the same IMX390 camera and that it works?
