### ISSUE TITLE
Ubuntu 18.04 Built copy fails to create preview window.

### ISSUE THREAD

**Issue by mhungerford-cpi** [LI01/linux_camera_tool#15]
There is a binary build checked-in (leopard_cam). 
That one works and the window doesn't crash. 

The one I built myself on Ubuntu 18.04 crashes. 
Both link to the same versions of libraries.

Error:
(Camera View:12943): GLib-GObject-CRITICAL **: 18:09:37.751: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by mhungerford-cpi** [comment]
similar issues were reported in:
https://github.com/LI01/linux_camera_tool/issues/14

**Comment by khalilsarwari** [comment]
@danyu9394 I believe the bug was introduced in `454154ed6430dce8fba9f28d2238bffbb96cf1bb`, the commits before then work for me, but the latest version of the code in the repo still has this error (#17 doesn't fix it for me at least)
